### ISSUE TITLE
Cannot "setup:install" new Magento app with module installed

### ISSUE THREAD

**Issue by mattwellss** [magemojo/m2-ce-cron#69] opened 2019-04-29 15:17 UTC
Requested info | Value
----|----
Magento version | 2.2.8
|executed|`./bin/magento setup:install`|
|expected|Fresh Magento app installed|
|actual|`[PDOException]...Base table or view not found: 1146 Table 'lfidb.core_config_data' doesn't exist`|

The problem is `MageMojo\Cron\Model\Schedule` requests `core_config_data` information eagerly. This can be mitigated by creating a `preference` for that class as a proxy:
```xml
<preference for="MageMojo\Cron\Model\Schedule" type="MageMojo\Cron\Model\Schedule\Proxy" />
```

**Comment by lukeconvertdigital** [comment] 2019-06-18 02:34
This also causes integration tests to fail.

**Comment by mattwellss** [comment] 2019-06-18 20:52
My recommendation above caused an infinite loop 😨. This is how we've patched it ourselves:
```patch
diff --git a/etc/di.xml b/etc/di.xml
index f74cbee9..c86efc49 100644
--- a/etc/di.xml
+++ b/etc/di.xml
@@ -15,5 +15,16 @@
             </argument>
         </arguments>
     </type>
+    <type name="MageMojo\Cron\Console\Command\CronCommand">
+        <arguments>
+            <argument name="schedule" xsi:type="object">MageMojo\Cron\Model\Schedule\Proxy</argument>
+        </arguments>
+    </type>
+
+    <type name="MageMojo\Cron\Console\Command\CronExecuteCommand">
+        <arguments>
+            <argument name="schedule" xsi:type="object">MageMojo\Cron\Model\Schedule\Proxy</argument>
+        </arguments>
+    </type>
 </config>
 ```

**Comment by ericvhileman** [comment] 2019-07-08 16:18
@mattwellss @lukeconvertdigital We're not able to reproduce on default 2.2.8.  What other extensions are in your installation?

cc @gnuzealot

**Comment by mattwellss** [comment] 2019-07-19 17:26
@ericvhileman to clarify: you can first install this module and then initialize the database? 

In my experience, [both the cron commands listed here](https://github.com/magemojo/m2-ce-cron/issues/69#issuecomment-503307209) read from `core_config_data` during their construction (or rather, one of their dependencies does). As such, when they're constructed as part of the CLI application init, a PDOException occurs, caused by the missing table.

**Comment by ericvhileman** [comment] 2019-07-19 17:43
@mattwellss we cannot reproduce on Open Source 2.2.8. Are you using Open Source or Commerce?

**Comment by gnuzealot** [comment] 2020-02-17 20:14
This was resolved in latest version.

**Closed by gnuzealot** 2020-02-17 20:14 UTC
