### ISSUE TITLE
magemojo all task pending

### ISSUE THREAD

**Issue by mpropl** [magemojo/m2-ce-cron#51] opened 2018-08-29 14:47 UTC
MageMojo hangs and does not want to perform cron tasks all have pending status

**Comment by blmage** [comment] 2018-09-20 16:44
Are you using the latest version? (1.2.5)
We had the same problem on a 1.2.3, and updating the module fixed it for us (certainly thanks to 5a32e4132b81454042bc8fac069e2781a4695979)

**Comment by gnuzealot** [comment] 2018-10-31 15:43
Not able to reproduce, assuming it's fixed in latest version.

**Closed by gnuzealot** 2018-10-31 15:43 UTC
